apiVersion: v1
kind: ConfigMap
metadata:
  name: eazybank-configmap
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
  SPRING_CLOUD_KUBERNETES_DISCOVERY_DISCOVERY_SERVER_URL: "http://spring-cloud-kubernetes-discoveryserver:80"
  SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: "kafka:9092"
  CONFIGSERVER_APPLICATION_NAME: "configserver"
  ACCOUNTS_APPLICATION_NAME: "accounts"
  LOANS_APPLICATION_NAME: "loans"
  CARDS_APPLICATION_NAME: "cards"
  GATEWAY_APPLICATION_NAME: "gatewayserver"
  MESSAGE_APPLICATION_NAME: "message"
  KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
  KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:7080/realms/master/protocol/openid-connect/certs"
