spring:
  application:
    name: configserver
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        #native:
          #search-locations: "classpath:/config"
          #search-locations: "file:///D://Spring Boot Microservices//User//config"
        git:
          uri: "https://github.com/ArjunKhade/easybank-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

encrypt:
  key: "S4D75HK96BH5TFAHL8ADVAJKKBD"

server:
  port: 8071
